language: rust
sudo: false
dist: trusty
rust:
  - stable
  - nightly

cache:
  cargo: true

matrix:
  allow_failures:
   - rust: nightly

script:
  - |
    cargo test --test lib
    cargo test --release --test lib
    cargo build --example basic
    cargo build --release --example basic
    cargo build --example actix --features actix
    cargo build --release --example actix --features actix