language: rust
sudo: false
dist: trusty
rust:
  - stable
  - nightly

cache:
  cargo: true

matrix:
  allow_failures:
   - rust: nightly

script:
  - |
    cargo test --lib
    cargo test --lib --release
    cargo build --example basic
    cargo build --release --example basic