language: rust
sudo: false
dist: trusty
rust:
  - stable
  - nightly

cache:
  cargo: true

matrix:
  allow_failures:
   - rust: nightly

script:
  - cargo test --test lib
  - cargo test --test lib --release
  - cargo build --example basic
  - cargo build --example basic --release 
  - cargo build --example actix --features actix
  - cargo build --example actix --features actix --release
