language: rust
sudo: false
dist: trusty

cache:
  cargo: true

matrix:
  include:
    - rust: nightly

script:
  - |
    cargo clean
    cargo test --tests --lib
    cargo test --tests --lib --release
    cargo clean
    cargo build --example basic
    cargo clean
    cargo build --release --example basic