[package]
name = "rust-embed"
version = "0.2.0"
description = "Generates rust code to embed resource files into your rust executable"
readme = "README.md"
documentation = "https://docs.rs/rust-embed"
repository = "https://github.com/pyros2097/rust-embed"
license = "MIT"
keywords = ["http", "rocket", "static", "web", "server"]
categories = ["web-programming::http-server"]
authors = ["pyros2097 <pyros2097@gmail.com>"]

[dev-dependencies]
hyper = "*"
