name: Test
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@master
      - name: Run tests
        run: |
          - cargo test --test lib
          - cargo test --test lib --features "debug-embed"
          - cargo test --test lib --release
          - cargo test --test lib --features "compression" --release
          - cargo test --test interpolated_path --features "interpolate-folder-path"
          - cargo test --test interpolated_path --features "interpolate-folder-path" --release
          - cargo build --example basic
          - cargo build --example basic --release
          - cargo build --example actix --features actix
          - cargo build --example actix --features actix --release
          - cargo build --example warp --features warp-ex
          - cargo build --example warp --features warp-ex --release
