name: Test
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]
        experimental: [false, true]
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - uses: actions/checkout@master
      - name: Run tests
        run: |
          cargo fmt --all -- --check
          cargo test --test lib
          cargo test --test lib --features "debug-embed"
          cargo test --test lib --features "compression" --release
          cargo test --test interpolated_path --features "interpolate-folder-path"
          cargo test --test interpolated_path --features "interpolate-folder-path" --release
          cargo build --example basic
          cargo build --example actix --features actix
          cargo build --example warp --features warp-ex
          cargo test --test lib --release
          cargo build --example basic --release
          cargo build --example actix --features actix --release
          cargo build --example warp --features warp-ex --release
